// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOanhyuKa2bXYBvE58LxPceLKbiC0c-nU',
    appId: '1:223481925154:web:c7d854423102339537847b',
    messagingSenderId: '223481925154',
    projectId: 'project-87cab',
    authDomain: 'project-87cab.firebaseapp.com',
    storageBucket: 'project-87cab.firebasestorage.app',
    measurementId: 'G-MGPL78MFPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLxUvPgEX0TrZSZJ3dNcgjG39nwNJ_qJQ',
    appId: '1:223481925154:android:69992793bdf7d18b37847b',
    messagingSenderId: '223481925154',
    projectId: 'project-87cab',
    storageBucket: 'project-87cab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOe8h7x7pDI4x4YjbZWDRELkP09MHyQww',
    appId: '1:223481925154:ios:e010db91433d146237847b',
    messagingSenderId: '223481925154',
    projectId: 'project-87cab',
    storageBucket: 'project-87cab.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOe8h7x7pDI4x4YjbZWDRELkP09MHyQww',
    appId: '1:223481925154:ios:e010db91433d146237847b',
    messagingSenderId: '223481925154',
    projectId: 'project-87cab',
    storageBucket: 'project-87cab.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOanhyuKa2bXYBvE58LxPceLKbiC0c-nU',
    appId: '1:223481925154:web:400631e1631957c037847b',
    messagingSenderId: '223481925154',
    projectId: 'project-87cab',
    authDomain: 'project-87cab.firebaseapp.com',
    storageBucket: 'project-87cab.firebasestorage.app',
    measurementId: 'G-49VD21K6VF',
  );
}
