name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  flutter:
    name: Flutter Workflow
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      # Step 2: Set up Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2.18.0
        with:
          channel: stable
          flutter-version: '3.24.5'

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: flutter pub get

      # Step 4: Run Code Formatter (dart format)
      - name: Format Code
        run: dart format .

      # Step 5: Run Linter (dart analyze)
      - name: Lint Code
        run: flutter analyze || echo "Linting issues found"

      # Step 6: Run Tests
      - name: Run Tests
        run: flutter test
